- name: install apt packages
  hosts: localhost
  become: true

  tasks:
  - name: install git
    apt:
      name: git
      state: present

  - name: install vim
    apt:
      name: vim
      state: present

  - name: install pip
    apt:
      name: python3-pip
      state: present